=== jaiseejagan/tema03/facturasValid.dtd
<!--ELEMENTOS RAIZ!-->

<!ELEMENT listadoFacturas (membrete, clientes, productos, facturas)>

<!ATTLIST listadoFacturas 
            lang CDATA #FIXED "es">

<!--ATRIBUTOS MEMBRETE RAIZ!-->

<!ELEMENT membrete EMPTY>
<!ATTLIST membrete 
            cif CDATA #REQUIRED
            nombreEmpresa CDATA #REQUIRED
            web CDATA #REQUIRED
            direccion CDATA #REQUIRED
            codigoPostal CDATA #REQUIRED
            poblacion CDATA #REQUIRED
            telefono CDATA #REQUIRED
            email CDATA #REQUIRED>


<!--ELEMENTOS Y ATRIBUTOS DE CLIENTES!-->

<!ELEMENT clientes (cliente+)>
<!ELEMENT cliente EMPTY>
<!ATTLIST cliente
            idCliente ID #REQUIRED
            dni CDATA #REQUIRED
            nombre CDATA #REQUIRED
            apellidos CDATA #REQUIRED
            direccionFacturacion CDATA #REQUIRED
            codigoPostal CDATA #REQUIRED
            poblacion CDATA #REQUIRED>

<!--ELEMENTOS Y ATRIBUTOS DE PRODUCTOS!-->

<!ELEMENT productos (producto+)>
<!ELEMENT producto (descripcion)>
<!ELEMENT descripcion (#PCDATA)>
<!ATTLIST producto
            idProducto ID #REQUIRED
            precioUnitario CDATA #REQUIRED
            ivaAplicado CDATA #REQUIRED>

<!--ELEMENTOS Y ATRIBUTOS DE FACTURAS!-->

<!ELEMENT facturas (factura+)>
<!ELEMENT factura (destinatario, lineasFactura, resumenFactura)>
<!ELEMENT destinatario EMPTY>
<!ELEMENT lineasFactura (linea+)>
<!ELEMENT linea EMPTY>
<!ELEMENT resumenFactura EMPTY>

<!ATTLIST factura 
            numeroFactura ID #REQUIRED
            fechaEmision CDATA #REQUIRED>

<!ATTLIST destinatario
            idRefCliente IDREFS #REQUIRED>

<!ATTLIST linea
            idRefProducto IDREFS #REQUIRED
            unidadesAdquiridas CDATA #REQUIRED>

<!ATTLIST resumenFactura
            descuento (true|false) #REQUIRED
            porcentajeDescuento CDATA #IMPLIED
            metodoPago (efectivo|tarjeta|transferencia) #REQUIRED>

=== jaiseejagan/tema03/facturas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE listadoFacturas SYSTEM "facturasValid.dtd">

<listadoFacturas lang="es">

    <membrete cif="M01921322" nombreEmpresa="PaperAB" web="www.paperab.es" direccion="Calle Benissa" codigoPostal="28001" poblacion="Madrid" telefono="601901223" email="paperab@gmail.com"/>
        
    <clientes>

        <cliente idCliente="C1" dni="61023912Z" nombre="Mateo Higueras" apellidos="Pesti" direccionFacturacion="Calle Valencia" codigoPostal="28010" poblacion="Madrid"/>

        <cliente idCliente="C2" dni="01029312B" nombre="Maria Serra" apellidos="Lana" direccionFacturacion="Calle Juan Carlos I" codigoPostal="2800" poblacion="Madrid"/>

        <cliente idCliente="C3" dni="10221401A" nombre="Josep Ivars" apellidos="Marcas" direccionFacturacion="Calle Pedrera" codigoPostal="2901" poblacion="Valencia"/>
            

    </clientes> 

    <productos>
        
        <producto idProducto="P1" precioUnitario="6€" ivaAplicado="21" >

            <descripcion>Láminas de papel</descripcion>
        
         </producto>
            
        <producto idProducto="P2" precioUnitario="1€" ivaAplicado="21">
            
            <descripcion>Lápiz</descripcion>
        
        </producto>

        <producto idProducto="P3" precioUnitario="15€" ivaAplicado="21">
            
            <descripcion>Pack Subrayadores</descripcion>
            
        </producto>

    </productos>


    <facturas>

        <factura numeroFactura="F1" fechaEmision="30-10-2024">

            <destinatario idRefCliente="C1"/>

            <lineasFactura>

                <linea idRefProducto="P1" unidadesAdquiridas="5"/>
                <linea idRefProducto="P2" unidadesAdquiridas="10"/>
                <linea idRefProducto="P3" unidadesAdquiridas="30"/>
                
           </lineasFactura>

           <resumenFactura descuento="true" porcentajeDescuento="10" metodoPago="efectivo"/>

        </factura>

        <factura numeroFactura="F2" fechaEmision="31-10-2024">

            <destinatario idRefCliente="C3"/>

            <lineasFactura>

                <linea idRefProducto="P1" unidadesAdquiridas="1"/>
                <linea idRefProducto="P2" unidadesAdquiridas="6"/>
                <linea idRefProducto="P3" unidadesAdquiridas="5"/>
                
           </lineasFactura>

           <resumenFactura descuento="false" metodoPago="tarjeta"/>

        </factura>

    </facturas>

</listadoFacturas>
