=== jaiseejagan/tema03/figuras.dtd
<!-- DTD SOBRE EL ARCHIVO XML DE FIGURAS GEOMÉTRICAS-->

<!--ELEMENTO RAÍZ Y ELEMENTOS DENTRO GENERALES-->

<!ELEMENT escena (figuras)>
<!ELEMENT figuras (rectangulo, circumferencia, linea)>


<!--ELEMENTOS Y ATRIBUTOS DEL RECTÁNGULO-->

<!ELEMENT rectangulo (posicionA)>
<!ELEMENT posicionA (x, y)>
<!ELEMENT x (#PCDATA)>
<!ELEMENT y (#PCDATA)>

<!ATTLIST rectangulo 
            ancho CDATA #REQUIRED 
            alto CDATA #REQUIRED>


<!--ELEMENTOS Y ATRIBUTOS DE LA CIRCUMFERENCIA-->

<!ELEMENT circumferencia (posicionB)>
<!ELEMENT posicionB (x2,y2)>
<!ELEMENT x2 (#PCDATA)>
<!ELEMENT y2 (#PCDATA)>

<!ATTLIST circumferencia 
            radio CDATA #REQUIRED>


<!--ELEMENTOS Y ATRIBUTOS DE LA LÍNEA-->

<!ELEMENT linea (posicionC)>

<!ELEMENT x3 (#PCDATA)>
<!ELEMENT y3 (#PCDATA)>
<!ELEMENT posicionC (origen, destino)>
<!ELEMENT origen (x3, y3)>
<!ELEMENT destino (x4, y4)>
<!ELEMENT x4 (#PCDATA)>
<!ELEMENT y4 (#PCDATA)>

<!ATTLIST linea 
            largo CDATA #REQUIRED>

=== jaiseejagan/tema03/figuras_geometricas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE escena SYSTEM "figuras.dtd">
 
<escena>

    <figuras>

        <rectangulo ancho="150px" alto="120px">
             
            <posicionA>
                <x>150</x>
                <y>400</y>
            </posicionA>

        </rectangulo>

        <circumferencia radio="100px">

            <posicionB>
                <x2>400</x2>
                <y2>400</y2>
            </posicionB>

        </circumferencia>    

        <linea largo="100px">
            
        <posicionC>

            <origen>
                <x3>300</x3>
                <y3>400</y3>
            </origen>

            <destino>
                <x4>400</x4>
                <y4>520</y4>
            </destino>

        </posicionC>

    </linea>

</figuras>

</escena>
