=== jaiseejagan/tema03/tickets.dtd
<!--ELMENTOS RAIZ Y ELEMENTOS GENERALES!-->

<!ELEMENT ticketsVenta (ticket+)>
<!ELEMENT ticket (cabeceraTicket+, ventas*, resumenVentas)>

<!ELEMENT cabeceraTicket EMPTY>

<!ELEMENT ventas (venta+)>
<!ELEMENT venta (descripcionProducto)>
<!ELEMENT descripcionProducto (#PCDATA)>

<!ELEMENT resumenVentas EMPTY>


<!--ATRIBUTOS!-->

<!ATTLIST ticketsVenta
            empresa CDATA #FIXED "PapeleriaD"
            lang CDATA #FIXED "es">

<!ATTLIST ticket 
            sucursal CDATA #REQUIRED
            cif CDATA #REQUIRED
            web CDATA #REQUIRED
            telefono CDATA #REQUIRED
            codigoSucursal CDATA #REQUIRED
            direccion CDATA #REQUIRED
            ciudad CDATA #REQUIRED
            codigoPostal CDATA #REQUIRED>


<!ATTLIST cabeceraTicket
            empleado CDATA #REQUIRED
            id ID #REQUIRED
            diaSemana (lunes|martes|miercoles|jueves|viernes) #REQUIRED
            dia (1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31) #REQUIRED
            mes (enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|octubre|noviembre|deciembre) #REQUIRED
            aÃ±o (2022|2023|2024|2025|2026|2027|2028|2029|2030|2031|2032|2033|2034|2035|2036|2037|2038|2039|2040) #REQUIRED
            hora CDATA #REQUIRED>

<!ATTLIST venta 
            nombreProducto CDATA #REQUIRED
            idProducto CDATA #REQUIRED
            cantidad CDATA #REQUIRED
            precioUnidad CDATA #REQUIRED
            oferta (true|false) #REQUIRED
            porcentajeDescuento (0|10|20|30|40|50) #IMPLIED
            precioTotal CDATA #REQUIRED>

<!ATTLIST resumenVentas
            idVenta ID #REQUIRED
            metodoPago (tarjeta|efectivo) #REQUIRED
            importeTotal CDATA #REQUIRED>

=== jaiseejagan/tema03/listadoTickets.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ticketsVenta SYSTEM "tickets.dtd"> 

<ticketsVenta empresa="PapeleriaD" lang="es">

    <ticket sucursal="PapeleriaD1" cif="10923121A" web="www.papeleriad1.com" telefono="601982310" codigoSucursal="E120102" direccion="Calle Joaquin Costa" ciudad="Valencia" codigoPostal="46005">

        <cabeceraTicket empleado="Jose Martin Morales" id="T1" diaSemana="lunes" dia="18" mes="noviembre" año="2024" hora="10:00"/>

        <ventas>

            <venta nombreProducto="Lápiz de grafito" idProducto="P1" cantidad="100" precioUnidad="1€" oferta="true" porcentajeDescuento="10" precioTotal="90€">

                <descripcionProducto>
                    Lápiz de grafito ideal para escribir o dibujar 
                </descripcionProducto>

            </venta>

            <venta nombreProducto="Goma de Borrar" idProducto="P2" cantidad="2" precioUnidad="0,5€" oferta="false" precioTotal="1€">
    
                    <descripcionProducto>
                        Goma de borrar de la marca Manley
                    </descripcionProducto>
    
            </venta>


            <venta nombreProducto="Tijeras" idProducto="P3" cantidad="1" precioUnidad="1€" oferta="false" precioTotal="1€">
    
                    <descripcionProducto>
                        Tijeras pequeñas de la marca Cutty
                    </descripcionProducto>
    
            </venta>

        
        </ventas>

        <resumenVentas idVenta="V1" importeTotal="92€" metodoPago="tarjeta"/>
        
    </ticket>

    <ticket sucursal="PapeleriaD2" cif="10923121A" web="www.papeleriad2.com" telefono="640112091" codigoSucursal="E120311" direccion="Calle LaCosta" ciudad="Madrid" codigoPostal="3002">

        <cabeceraTicket empleado="Maria Moncho Higuera" id="T2" diaSemana="lunes" dia="18" mes="noviembre" año="2024" hora="12:00"/>

        <ventas>

            <venta nombreProducto="Lápiz de grafito" idProducto="P1" cantidad="50" precioUnidad="1€" oferta="true" porcentajeDescuento="10" precioTotal="45€">

                <descripcionProducto>
                    Lápiz de grafito ideal para escribir o dibujar 
                </descripcionProducto>
                
            </venta>

            <venta nombreProducto="Pack boligrafos" idProducto="P4" cantidad="30" precioUnidad="3€" oferta="true" porcentajeDescuento="10" precioTotal="81€">

                <descripcionProducto>
                    Pack de bolígrafos de diferentes colores de la marca BIC
                </descripcionProducto>
                
            </venta>

            <venta nombreProducto="Sacapuntas" idProducto="P5" cantidad="1" precioUnidad="1€" oferta="false" precioTotal="1€">

                <descripcionProducto>
                    Sacapuntas para lápices de la marca RICO
                </descripcionProducto>
                
            </venta>
        
        </ventas>

        <resumenVentas idVenta="V2" importeTotal="127€" metodoPago="efectivo"/>
        
    </ticket>

</ticketsVenta>
