=== jaiseejagan/tema03/tresenraya.dtd
<!--DOCUMENTO DE VALIDACIÃ“N DEL XML DE TRES EN RAYA!-->


<!--ELEMENTOS RAIZ!-->

<!ELEMENT tresEnRaya (partidasGuardadas)>
<!ELEMENT partidasGuardadas (partida+)>

<!ATTLIST tresEnRaya lang CDATA #FIXED "es">
<!--ELEMENTOS Y ATRIBUTOS DE "PARTIDA"!-->

<!ELEMENT partida (jugadores, turnosJugados, ganador*)>

<!ATTLIST partida 
            id ID #REQUIRED
            estado (incompleta|completada) #REQUIRED>

<!--ELEMENTO DE JUGADORES!-->

<!ELEMENT jugadores (jugador+)>
<!ELEMENT jugador (#PCDATA)>

<!ATTLIST partida 
            id ID #REQUIRED
            estado (incompleta|completada) #REQUIRED>

<!--ELEMENTOS Y ATRIBUTOS DE TURNOS JUGADOS!-->

<!ELEMENT turnosJugados (turno+)>
<!ELEMENT turno EMPTY>

<!ATTLIST turno
            movimiento ID #REQUIRED
            ficha (X|O) #REQUIRED
            posesion CDATA #REQUIRED
            posicionJugada (A1|A2|A3|B1|B2|B3|C1|C2|C3) #REQUIRED>

=== jaiseejagan/tema03/3enraya.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tresEnRaya SYSTEM "tresenraya.dtd">

<tresEnRaya lang="es">

    <partidasGuardadas>

        <partida id="P1" estado="completada">

            <!-- REPRESENTACIÃ“N DEL FUNCIONAMIENTO Y SISTEMA DEL JUEGO

                   A   B   C
                  ___ ___ ___
              1  |_O_|_X_|_O_|
              2  |_O_|_X_|_O_|
              3  |_X_|_O_|_X_|
        
            -->

            <jugadores>

                <jugador>Mateo</jugador>
                <jugador>Manuel</jugador>

            </jugadores>
        
            <turnosJugados>

                <turno movimiento="M1" ficha="O" posesion="Mateo" posicionJugada="A1"></turno> 
            
                <turno movimiento="M2" ficha="X" posesion="Manuel" posicionJugada="B2"></turno> 

                <turno movimiento="M3" ficha="O" posesion="Mateo" posicionJugada="A2"></turno> 
               
                <turno movimiento="M4" ficha="X" posesion="Manuel" posicionJugada="A3"></turno>

                <turno movimiento="M5" ficha="O" posesion="Mateo" posicionJugada="B3"></turno>

                <turno movimiento="M6" ficha="X" posesion="Manuel" posicionJugada="C3"></turno>
                
                <turno movimiento="M7" ficha="O" posesion="Mateo" posicionJugada="C2"></turno>

                <turno movimiento="M8" ficha="X" posesion="Manuel" posicionJugada="B1"></turno>

                <turno movimiento="M9" ficha="O" posesion="Mateo" posicionJugada="C1"></turno>
                
            </turnosJugados>

        </partida>

    </partidasGuardadas>


</tresEnRaya>
